package de.katzen48.datapack.highlighting;

public enum SemanticTokenType {
    ResourceLocation,
    String,
    IntegerArgumentType,
    ObjectiveArgument,
    ScoreHolderArgument,
    WorldCoordinates,
    Integer,
    SelectorResult,
    CompoundTag,
    NbtPath,
    Double,
    Ints,
    EntitySelector,
    OperationArgument,
    BlockInput,
    Reference,
    IntegerRange,
    ArgumentScoreholder,
    IChatMutableComponent,
    MinecraftKey,
    NBTTagCompound,
    Boolean,
    VectorPosition,
    IScoreboardCriteria,
    Statistic,
    ArgumentTileLocation,
    ArgumentPredicateItemStack,
    ParticleParamRedstone,
    Float,
    ArgumentMathOperation,
}
